# -*- coding: utf-8 -*-
"""BERT_phishing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/186XH9_QYUV8VUUpoQqbAX1FlEZa_yG9o

<a href="https://colab.research.google.com/github/ramyajeldy/Capstone_V2/blob/feature%2Fdataset/BERT_phishing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
"""

import torch
import numpy as np
import pandas as pd

from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer
)

import evaluate

dataset = load_dataset("drorrabin/phishing_emails-data")

dataset

print(dataset)
print(dataset["train"].column_names)
print(dataset["train"][0])

dataset["train"].to_pandas()["email_type"].value_counts()

def encode_labels(example):
    if example["email_type"] == "phishing email":
        example["labels"] = 1
    else:
        example["labels"] = 0
    return example

dataset = dataset.map(encode_labels)

dataset = dataset.remove_columns(["email_type"])

model_name = "bert-base-uncased"

tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize_function(example):
    return tokenizer(
        example["text"],
        truncation=True,
        padding="max_length",
        max_length=256
    )

tokenized_dataset = dataset.map(tokenize_function, batched=True)

tokenized_dataset.set_format("torch")

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=2
)

tokenized_dataset["train"][0]

set(dataset["train"]["labels"])

tokenized_dataset.set_format("torch")

tokenized_dataset["train"][0]

metric_accuracy = evaluate.load("accuracy")
metric_f1 = evaluate.load("f1")
metric_precision = evaluate.load("precision")
metric_recall = evaluate.load("recall")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)

    return {
        "accuracy": metric_accuracy.compute(predictions=predictions, references=labels)["accuracy"],
        "f1": metric_f1.compute(predictions=predictions, references=labels)["f1"],
        "precision": metric_precision.compute(predictions=predictions, references=labels)["precision"],
        "recall": metric_recall.compute(predictions=predictions, references=labels)["recall"],
    }

training_args = TrainingArguments(
    output_dir="./bert_results",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    load_best_model_at_end=True,
    report_to="tensorboard"   # ✅ new way
)

torch.cuda.is_available()

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["test"],
    compute_metrics=compute_metrics
)

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=2
)
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["test"],
    compute_metrics=compute_metrics
)
trainer.train()

trainer.evaluate()

trainer.state.best_model_checkpoint

trainer.evaluate()

predictions = trainer.predict(tokenized_dataset["test"])

import torch
import numpy as np
from torch.nn.functional import softmax

logits = torch.tensor(predictions.predictions)
probs = softmax(logits, dim=1).numpy()

phishing_probs = probs[:, 1]
true_labels = predictions.label_ids

from sklearn.metrics import f1_score

best_f1 = 0
best_threshold = 0.5

for t in np.arange(0.1, 0.9, 0.01):
    preds = (phishing_probs >= t).astype(int)
    f1 = f1_score(true_labels, preds)

    if f1 > best_f1:
        best_f1 = f1
        best_threshold = t

print("Best Threshold:", best_threshold)
print("Best F1:", best_f1)

from sklearn.metrics import precision_score, recall_score

optimal_preds = (phishing_probs >= 0.11).astype(int)

print("Precision:", precision_score(true_labels, optimal_preds))
print("Recall:", recall_score(true_labels, optimal_preds))
print("F1:", f1_score(true_labels, optimal_preds))

THRESHOLD = 0.12

def predict_email(text):
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=256
    ).to(model.device)

    with torch.no_grad():
        outputs = model(**inputs)
        probs = torch.nn.functional.softmax(outputs.logits, dim=1)

    phishing_prob = probs[0][1].item()

    return {
        "risk_score": round(phishing_prob, 4),
        "confidence": round(max(probs[0]).item(), 4),
        "label": "high_risk" if phishing_prob >= THRESHOLD else "low_risk"
    }

trainer.save_model("/content/phishing_bert_final")
tokenizer.save_pretrained("/content/phishing_bert_final")

import shutil
from google.colab import files

shutil.make_archive("phishing_bert_final", 'zip', "/content/phishing_bert_final")
files.download("phishing_bert_final.zip")