# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tIr3al9JlWKRLYDQBlDGCkNWCLoIZQjN
"""

# =========================
# FAKE JOB DETECTION - COLAB READY
# =========================

# Install dependencies
!pip -q install transformers datasets accelerate scikit-learn pandas

import os
import json
import random
import shutil
import numpy as np
import pandas as pd
import torch

from dataclasses import dataclass
from google.colab import drive
from datasets import load_dataset, DatasetDict
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
    confusion_matrix,
)
from sklearn.utils.class_weight import compute_class_weight
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments,
    EarlyStoppingCallback,
    set_seed,
)

# -------------------------
# CONFIG
# -------------------------
SEED = 42
MODEL_NAME = "distilbert-base-uncased"
DATASET_NAME = "james-burton/fake_job_postings2_ord"
MAX_LENGTH = 256
NUM_EPOCHS = 3
TRAIN_BATCH_SIZE = 8
EVAL_BATCH_SIZE = 8
LEARNING_RATE = 2e-5
THRESHOLD = 0.35
OUTPUT_DIR = "/content/fake_job_model"
DRIVE_SAVE_DIR = "/content/drive/MyDrive/capstone 2"

set_seed(SEED)
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

# -------------------------
# MOUNT GOOGLE DRIVE
# -------------------------
drive.mount("/content/drive")

# -------------------------
# LOAD DATASET
# -------------------------
dataset = load_dataset(DATASET_NAME)
print(dataset)

# -------------------------
# TEXT PREP
# -------------------------
def safe_str(value):
    if value is None:
        return ""
    return str(value).strip()

def build_job_text(example):
    fields = [
        safe_str(example.get("title", "")),
        safe_str(example.get("description", "")),
        safe_str(example.get("required_experience", "")),
        safe_str(example.get("required_education", "")),
        safe_str(example.get("salary_range", "")),
        safe_str(example.get("company_profile", "")),
        safe_str(example.get("benefits", "")),
        safe_str(example.get("requirements", "")),
        safe_str(example.get("industry", "")),
        safe_str(example.get("function", "")),
        safe_str(example.get("location", "")),
    ]
    text = " ".join([x for x in fields if x])
    return {"text": text}

text_dataset = DatasetDict({
    "train": dataset["train"].map(build_job_text),
    "validation": dataset["validation"].map(build_job_text),
    "test": dataset["test"].map(build_job_text),
})

print("Sample text:")
print(text_dataset["train"][0]["text"][:500])

# -------------------------
# TOKENIZER
# -------------------------
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

def tokenize_function(batch):
    return tokenizer(
        batch["text"],
        truncation=True,
        padding="max_length",
        max_length=MAX_LENGTH,
    )

tokenized = text_dataset.map(tokenize_function, batched=True)

def to_int_label(example):
    return {"labels": int(example["fraudulent"])}

tokenized = tokenized.map(to_int_label)

keep_columns = {"input_ids", "attention_mask", "labels"}
remove_columns = [c for c in tokenized["train"].column_names if c not in keep_columns]
tokenized = tokenized.remove_columns(remove_columns)
tokenized.set_format("torch")

print(tokenized)

# -------------------------
# CLASS WEIGHTS FOR IMBALANCE
# -------------------------
train_labels = np.array(tokenized["train"]["labels"])
class_weights = compute_class_weight(
    class_weight="balanced",
    classes=np.array([0, 1]),
    y=train_labels,
)
class_weights = torch.tensor(class_weights, dtype=torch.float)
print("Class weights:", class_weights)

# -------------------------
# MODEL
# -------------------------
model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=2,
)

# -------------------------
# METRICS WITH RECALL FOCUS
# -------------------------
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    probs = torch.softmax(torch.tensor(logits), dim=-1).numpy()
    preds = (probs[:, 1] >= THRESHOLD).astype(int)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, preds, average="binary", zero_division=0
    )
    accuracy = accuracy_score(labels, preds)

    cm = confusion_matrix(labels, preds, labels=[0, 1])
    tn, fp, fn, tp = cm.ravel()

    return {
        "accuracy": float(accuracy),
        "precision": float(precision),
        "recall": float(recall),
        "f1": float(f1),
        "tn": int(tn),
        "fp": int(fp),
        "fn": int(fn),
        "tp": int(tp),
    }

# -------------------------
# CUSTOM TRAINER WITH WEIGHTED LOSS
# -------------------------
class WeightedTrainer(Trainer):
    def __init__(self, class_weights=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.class_weights = class_weights

    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.get("labels")
        outputs = model(**inputs)
        logits = outputs.get("logits")

        loss_fct = torch.nn.CrossEntropyLoss(weight=self.class_weights.to(logits.device))
        loss = loss_fct(logits.view(-1, model.config.num_labels), labels.view(-1))

        return (loss, outputs) if return_outputs else loss

# -------------------------
# TRAINING ARGS
# -------------------------
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="epoch",
    learning_rate=LEARNING_RATE,
    per_device_train_batch_size=TRAIN_BATCH_SIZE,
    per_device_eval_batch_size=EVAL_BATCH_SIZE,
    num_train_epochs=NUM_EPOCHS,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="eval_recall",
    greater_is_better=True,
    save_total_limit=2,
    report_to="none",
    fp16=torch.cuda.is_available(),
)

# -------------------------
# TRAINER
# -------------------------
trainer = WeightedTrainer(
    class_weights=class_weights,
    model=model,
    args=training_args,
    train_dataset=tokenized["train"],
    eval_dataset=tokenized["validation"],
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)],
)

# -------------------------
# TRAIN
# -------------------------
trainer.train()

# -------------------------
# EVALUATE
# -------------------------
metrics = trainer.evaluate(tokenized["test"])
print("\nTest metrics:")
print(json.dumps(metrics, indent=2))

# -------------------------
# SAVE MODEL LOCALLY IN COLAB
# -------------------------
os.makedirs(OUTPUT_DIR, exist_ok=True)
trainer.save_model(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

with open(f"{OUTPUT_DIR}/metrics.json", "w") as f:
    json.dump(metrics, f, indent=2)

config_info = {
    "model_name": MODEL_NAME,
    "dataset_name": DATASET_NAME,
    "max_length": MAX_LENGTH,
    "num_epochs": NUM_EPOCHS,
    "train_batch_size": TRAIN_BATCH_SIZE,
    "eval_batch_size": EVAL_BATCH_SIZE,
    "learning_rate": LEARNING_RATE,
    "threshold": THRESHOLD,
}
with open(f"{OUTPUT_DIR}/training_config.json", "w") as f:
    json.dump(config_info, f, indent=2)

print("\nSaved locally to:", OUTPUT_DIR)

# -------------------------
# COPY MODEL TO GOOGLE DRIVE
# -------------------------
if os.path.exists(DRIVE_SAVE_DIR):
    shutil.rmtree(DRIVE_SAVE_DIR)

shutil.copytree(OUTPUT_DIR, DRIVE_SAVE_DIR)
print("Saved to Google Drive:", DRIVE_SAVE_DIR)

# -------------------------
# SIMPLE INFERENCE HELPERS
# -------------------------
inference_tokenizer = AutoTokenizer.from_pretrained(DRIVE_SAVE_DIR)
inference_model = AutoModelForSequenceClassification.from_pretrained(DRIVE_SAVE_DIR).to(device)
inference_model.eval()

def predict_job_text(text, threshold=THRESHOLD):
    if not text or not text.strip():
        return {
            "label": "unknown",
            "is_fake_job": False,
            "fraud_probability": 0.0,
            "legitimate_probability": 0.0,
            "confidence": 0.0,
            "message": "Empty input text."
        }

    inputs = inference_tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding="max_length",
        max_length=MAX_LENGTH,
    )
    inputs = {k: v.to(device) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = inference_model(**inputs)
        probs = torch.softmax(outputs.logits, dim=-1).cpu().numpy()[0]

    legit_prob = float(probs[0])
    fraud_prob = float(probs[1])
    predicted_label = 1 if fraud_prob >= threshold else 0

    return {
        "label": "fake_job" if predicted_label == 1 else "legitimate_job",
        "is_fake_job": predicted_label == 1,
        "fraud_probability": round(fraud_prob, 4),
        "legitimate_probability": round(legit_prob, 4),
        "confidence": round(max(legit_prob, fraud_prob), 4),
        "threshold_used": threshold,
    }

# -------------------------
# QUICK TESTS
# -------------------------
sample_fake = """
Work from home and earn $5000 weekly with no experience.
Immediate joining. No interview. Free laptop. Send your bank details to begin.
"""

sample_real = """
We are hiring a Software Engineer with 3+ years of Python experience.
Responsibilities include backend API development, testing, and deployment.
Bachelor's degree preferred.
"""

print("\nFake sample prediction:")
print(predict_job_text(sample_fake))

print("\nReal sample prediction:")
print(predict_job_text(sample_real))

"""### Set Hugging Face Token (Optional but Recommended)

To avoid rate limiting and get the most out of Hugging Face Hub, it's recommended to set your Hugging Face API token. You can obtain one from [Hugging Face settings](https://huggingface.co/settings/tokens).

Once you have your token, add it to Colab secrets (the 🔑 icon in the left sidebar) with the name `HF_TOKEN`.
"""

from google.colab import userdata
import os

try:
    HF_TOKEN = userdata.get('HF_TOKEN')
    os.environ['HF_TOKEN'] = HF_TOKEN
    print("Hugging Face token loaded from Colab secrets.")
except userdata.SecretNotFoundError:
    print("Hugging Face token not found in Colab secrets. Proceeding without authentication.")
    print("You may encounter rate limits or be unable to access private models.")